"""Initial migration 5

Revision ID: 5356941d91c7
Revises: 0509e96451a6
Create Date: 2023-12-22 08:41:11.693929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5356941d91c7'
down_revision: Union[str, None] = '0509e96451a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('abc', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'abc')
    # ### end Alembic commands ###
